# Generated by Django 4.0.4 on 2022-07-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Robotics', 'Robotics'), ('Automobile', 'Automobile'), ('Machine', 'Machine')], max_length=200)),
                ('qty', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(choices=[('Standard', 'Standard'), ('Custom', 'Custom')], max_length=200)),
                ('status', models.CharField(choices=[('Not Start', 'Not Start'), ('In Progress', 'In Progress'), ('Change Order', 'Change Order'), ('Done', 'Done'), ('Deliver', 'Deliver'), ('Approve', 'Approve')], max_length=200)),
            ],
        ),
    ]
