# Generated by Django 4.0.4 on 2022-07-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='status',
        ),
    ]
