# Generated by Django 4.0.4 on 2022-07-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_remove_products_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
