# Generated by Django 4.0.4 on 2022-07-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_products_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='number',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
