# Generated by Django 4.0.4 on 2022-07-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_remove_products_id_products_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img',
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Custom', 'Custom')], max_length=200, null=True),
        ),
    ]
