# Generated by Django 4.0.4 on 2022-05-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('team', models.CharField(choices=[('Robotics', 'Robotics'), ('Automobile', 'Automobile'), ('Machine', 'Machine')], max_length=200)),
                ('position', models.CharField(choices=[('Manager', 'Manager'), ('Sales', 'Sales'), ('Engineer', 'Engineer'), ('Warehouse', 'Warehouse')], max_length=200)),
            ],
        ),
    ]
