# Generated by Django 4.0.4 on 2022-07-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='status',
        ),
    ]
