# Generated by Django 4.0.4 on 2022-07-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_sell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s_num', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('team', models.CharField(choices=[('Robotics', 'Robotics'), ('Automobile', 'Automobile'), ('Machine', 'Machine')], max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Complete', 'Complete'), ('Cancel', 'Cancel'), ('Revision', 'Revision')], max_length=200)),
                ('category', models.CharField(choices=[('Manager', 'Manager'), ('Sales', 'Sales'), ('Engineer', 'Engineer'), ('Warehouse', 'Warehouse')], max_length=200)),
                ('item', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='p_num',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
