# Generated by Django 4.0.4 on 2022-07-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_sell', '0003_alter_purchase_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='items',
        ),
        migrations.AddField(
            model_name='purchase',
            name='item',
            field=models.CharField(default='', max_length=200),
        ),
    ]
