# Generated by Django 4.0.4 on 2022-07-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_sell', '0004_remove_purchase_items_purchase_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='selling',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
