# Generated by Django 4.0.4 on 2022-07-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_sell', '0005_alter_purchase_date_alter_selling_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='selling',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
