# Generated by Django 4.0.4 on 2022-07-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_sell', '0006_alter_purchase_date_alter_selling_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selling',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
