# Generated by Django 4.0.4 on 2022-07-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_sell', '0007_purchase_qty_selling_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.CharField(choices=[('Robotics', 'Robotics'), ('Automobile', 'Automobile'), ('Machine', 'Machine')], max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='team',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Sales', 'Sales'), ('Engineer', 'Engineer'), ('Warehouse', 'Warehouse')], max_length=200),
        ),
        migrations.AlterField(
            model_name='selling',
            name='category',
            field=models.CharField(choices=[('Robotics', 'Robotics'), ('Automobile', 'Automobile'), ('Machine', 'Machine')], max_length=200),
        ),
        migrations.AlterField(
            model_name='selling',
            name='team',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Sales', 'Sales'), ('Engineer', 'Engineer'), ('Warehouse', 'Warehouse')], max_length=200),
        ),
    ]
