# Generated by Django 4.0.4 on 2022-07-06 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('customers', '0002_alter_customers_email'),
        ('buy_sell', '0008_alter_purchase_category_alter_purchase_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='suppliers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.suppliers'),
        ),
        migrations.AddField(
            model_name='selling',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customers'),
        ),
    ]
