# Generated by Django 4.0.4 on 2022-05-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventories_dashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('robot', models.IntegerField()),
                ('automobile', models.IntegerField()),
                ('machine', models.IntegerField()),
            ],
        ),
    ]
