# Generated by Django 4.0.4 on 2022-05-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('sender', models.CharField(max_length=200)),
                ('reciever', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outstanding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], max_length=200)),
                ('type', models.CharField(choices=[('Invoice', 'Invoice'), ('Change', 'Change'), ('Order', 'Order'), ('Finance', 'Finance')], max_length=200)),
                ('level', models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor')], max_length=200)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('tweet_by', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Inventories_dashboard',
        ),
    ]
