# Generated by Django 4.0.4 on 2022-07-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Need Refill', 'Need Refill'), ('Out of Stock', 'Out of Stock'), ('Pending', 'Pending')], max_length=200),
        ),
    ]
